spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/atomu?serverTimezone=GMT
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
mybatis:
  type-aliases-package: com.atomu.apiserver.entity
  mapper-locations: classpath:mapping/*.xml
meeting:
  max-created-num: 10
token:
  expire-time: 3600000
  api-server:
    secret: 405c1e6d-05be-447a-8a81-ca58190185ca
  msg-server:
    secret: 85fe55b5-ffc6-4ec9-a8dd-a3accf7924d3